# Generated by Django 5.2.7 on 2025-10-09 15:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "Lecture"),
                            ("ASSIGNMENT", "Assignment"),
                            ("LAB", "Lab"),
                            ("TUTORIAL", "Tutorial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("chapter", models.CharField(blank=True, max_length=255, null=True)),
                ("file", models.JSONField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content",
                "verbose_name_plural": "Contents",
                "db_table": "contents",
                "indexes": [
                    models.Index(fields=["course"], name="contents_course__06c913_idx"),
                    models.Index(fields=["type"], name="contents_type_e06012_idx"),
                    models.Index(fields=["tags"], name="contents_tags_0372ee_idx"),
                ],
            },
        ),
    ]
