# Generated by Django 5.2.7 on 2025-10-18 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("LECTURE", "Lecture"),
                            ("ASSIGNMENT", "Assignment"),
                            ("LAB", "Lab"),
                            ("TUTORIAL", "Tutorial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("path", models.CharField(max_length=255)),
                ("chapter", models.CharField(blank=True, max_length=255, null=True)),
                ("file", models.JSONField()),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Content",
                "verbose_name_plural": "Contents",
                "db_table": "contents",
            },
        ),
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Download Log",
                "verbose_name_plural": "Download Logs",
                "db_table": "download_logs",
            },
        ),
    ]
