# Generated by Django 5.2.7 on 2025-10-17 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0002_content_uploaded_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to="contents.content",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="download_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Download Log",
                "verbose_name_plural": "Download Logs",
                "db_table": "download_logs",
                "indexes": [
                    models.Index(
                        fields=["user"], name="download_lo_user_id_970f04_idx"
                    ),
                    models.Index(
                        fields=["content"], name="download_lo_content_be3601_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="download_lo_created_4ffce5_idx"
                    ),
                ],
            },
        ),
    ]
