# Generated by Django 5.2.7 on 2025-10-18 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contents", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_contents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="downloadlog",
            name="content",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_logs",
                to="contents.content",
            ),
        ),
        migrations.AddField(
            model_name="downloadlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="download_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["course"], name="contents_course__06c913_idx"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["type"], name="contents_type_e06012_idx"),
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(fields=["tags"], name="contents_tags_0372ee_idx"),
        ),
        migrations.AddIndex(
            model_name="downloadlog",
            index=models.Index(fields=["user"], name="download_lo_user_id_970f04_idx"),
        ),
        migrations.AddIndex(
            model_name="downloadlog",
            index=models.Index(
                fields=["content"], name="download_lo_content_be3601_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="downloadlog",
            index=models.Index(
                fields=["created_at"], name="download_lo_created_4ffce5_idx"
            ),
        ),
    ]
