# Generated by Django 5.2.7 on 2025-10-09 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saved_courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcourse",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="savedcourse",
            index=models.Index(fields=["user"], name="saved_cours_user_id_34cfe4_idx"),
        ),
        migrations.AddIndex(
            model_name="savedcourse",
            index=models.Index(fields=["course"], name="saved_cours_course__3ac50f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="savedcourse",
            unique_together={("user", "course")},
        ),
    ]
