# Generated by Django 5.2.7 on 2025-10-01 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("saved_courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="savedcourse",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="savedcourse",
            index=models.Index(fields=["user_id"], name="saved_cours_user_id_bc0d66_idx"),
        ),
        migrations.AddIndex(
            model_name="savedcourse",
            index=models.Index(fields=["course_id"], name="saved_cours_course__c9e0aa_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="savedcourse",
            unique_together={("user_id", "course_id")},
        ),
    ]
