# Generated by Django 5.2.7 on 2025-10-09 15:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("semester", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_offerings",
                        to="courses.course",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_offerings",
                        to="departments.department",
                    ),
                ),
            ],
            options={
                "db_table": "course_offerings",
                "indexes": [
                    models.Index(fields=["course"], name="course_offe_course__6bd727_idx"),
                    models.Index(fields=["department"], name="course_offe_departm_7e2f93_idx"),
                    models.Index(fields=["year", "semester"], name="course_offe_year_24682f_idx"),
                ],
            },
        ),
    ]
