# Generated by Django 5.2.7 on 2025-10-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("STUDENT", "student"),
                    ("LECTURER", "Lecturer"),
                    ("ADMIN", "admin"),
                    ("MODERATOR", "moderator"),
                ],
                default="STUDENT",
                max_length=20,
            ),
        ),
    ]
