# Generated by Django 5.2.7 on 2025-10-09 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course_assignments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="courseassignment",
            index=models.Index(fields=["user"], name="course_assi_user_id_fa6112_idx"),
        ),
        migrations.AddIndex(
            model_name="courseassignment",
            index=models.Index(fields=["course"], name="course_assi_course__5eb084_idx"),
        ),
    ]
