# Generated by Django 5.2.7 on 2025-10-18 14:28

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("semester", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_offerings",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("abbreviation", models.CharField(max_length=5)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPULSORY", "Compulsory"),
                            ("SUPPORTIVE", "Supportive"),
                            ("COMMON", "Common"),
                            ("ELECTIVE", "Elective"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credit_points", models.PositiveIntegerField(blank=True, null=True)),
                ("lecture_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("lab_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("tutorial_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("homework_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("credit_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "db_table": "courses",
                "indexes": [
                    models.Index(fields=["code"], name="courses_code_fa42f1_idx"),
                    models.Index(
                        fields=["abbreviation"], name="courses_abbrevi_eeb470_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["tags"], name="courses_tags_800383_gin"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_assignments",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_assignments",
            },
        ),
    ]
