# Generated by Django 5.2.7 on 2025-10-18 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courseassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_offerings",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="courseoffering",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_offerings",
                to="departments.department",
            ),
        ),
        migrations.AddIndex(
            model_name="courseassignment",
            index=models.Index(fields=["user"], name="course_assi_user_id_fa6112_idx"),
        ),
        migrations.AddIndex(
            model_name="courseassignment",
            index=models.Index(
                fields=["course"], name="course_assi_course__5eb084_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["course"], name="course_offe_course__6bd727_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["department"], name="course_offe_departm_7e2f93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseoffering",
            index=models.Index(
                fields=["year", "semester"], name="course_offe_year_24682f_idx"
            ),
        ),
    ]
