# Generated by Django 5.2.7 on 2025-10-05 05:58

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ACCESS", "Access"),
                            ("ROLE_CHANGE", "Role Change"),
                            ("DATA_UPDATE", "Data Update"),
                            ("COURSE_ASSIGNMENT", "Course Assignment"),
                            ("COMPLAIN", "Complain"),
                            ("FEEDBACK", "Feedback"),
                            ("LEAVE", "Leave"),
                            ("GRADE_REVIEW", "Grade Review"),
                            ("OTHER", "Other"),
                        ],
                        default="ACCESS",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("REJECTED", "Rejected"),
                            ("APPROVED", "Approved"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("full_name", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("staff_id", models.CharField(blank=True, max_length=50, null=True)),
                ("student_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "department_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "intake",
                "ordering": [
                    models.Case(
                        models.When(status="PENDING", then=0),
                        models.When(status="REJECTED", then=1),
                        models.When(status="APPROVED", then=2),
                        output_field=models.IntegerField(),
                    ),
                    "created_at",
                ],
                "indexes": [
                    models.Index(fields=["type"], name="intake_type_906c91_idx"),
                    models.Index(fields=["status"], name="intake_status_e757cd_idx"),
                ],
            },
        ),
    ]
