# Generated by Django 5.2.7 on 2025-10-09 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("intake", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="intakes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="intake",
            index=models.Index(fields=["type"], name="intake_type_906c91_idx"),
        ),
        migrations.AddIndex(
            model_name="intake",
            index=models.Index(fields=["status"], name="intake_status_e757cd_idx"),
        ),
    ]
