# Generated by Django 5.2.7 on 2025-10-17 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contents", "0003_downloadlog"),
        ("courses", "0001_initial"),
        ("intake", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="content",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intakes",
                to="contents.content",
            ),
        ),
        migrations.AddField(
            model_name="intake",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intakes",
                to="courses.course",
            ),
        ),
    ]
