# Generated by Django 5.2.7 on 2025-10-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_intake_content_intake_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="intake",
            name="subject",
            field=models.CharField(default="No Subject", max_length=150),
        ),
    ]
